version: '3.4'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Logging__Console__FormatterName=Simple"
      - "ConnectionStrings__DefaultConnection=User ID=postgres;Password=password;Host=host.docker.internal;Port=5432;Database=Inventory;Pooling=true;Connection Lifetime=0"
      - "PORT=5000"
    ports:
      - "5000:5000"
#      - "5001:5001"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
  #    volumes:
  #      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
  